"""Add context_id to access

Revision ID: 73d724432768
Revises: 359ab8aacbb9
Create Date: 2022-06-30 02:26:29.192048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d724432768'
down_revision = '359ab8aacbb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access', sa.Column('context_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'access', 'context', ['context_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_column('access', 'context_id')
    # ### end Alembic commands ###
