"""CASCADE delete for all

Revision ID: bb6c5e4149a0
Revises: e39e0665b282
Create Date: 2022-07-01 01:36:46.131249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6c5e4149a0'
down_revision = 'e39e0665b282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('access_user_id_fkey', 'access', type_='foreignkey')
    op.drop_constraint('access_context_id_fkey', 'access', type_='foreignkey')
    op.create_foreign_key(None, 'access', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'access', 'context', ['context_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.drop_constraint(None, 'access', type_='foreignkey')
    op.create_foreign_key('access_context_id_fkey', 'access', 'context', ['context_id'], ['id'])
    op.create_foreign_key('access_user_id_fkey', 'access', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
